name: cleanarchitecture
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.1.0
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mockito: ^5.4.2
  build_runner:
  bloc_test: ^9.1.4
  mocktail: ^1.0.0


flutter:
  fonts:    
      - family: MyFlutterApp
        fonts:
          - asset: assets/font/MyFlutterApp.ttf
      
      - family: Figtree
        fonts:
          - asset: assets/font/Figtree-Regular.ttf
    


  uses-material-design: true
  assets:
  - assets/font/
